apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: challenge-devops
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: challenge-devops
  targetCPUUtilizationPercentage: 50 # target CPU utilization